FROM --platform=arm64 ubuntu:22.04

RUN apt-get update && \
  apt-get upgrade -y

RUN apt-get install locales -y && \
  rm -rf /var/lib/apt/lists/* && \
  localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

ENV LANG en_US.utf8

RUN apt update
RUN DEBIAN_FRONTEND=noninteractive apt-get install postfix -y
